config/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('onlineschool/', include('onlineschool.urls')),
]

onlineschool/urls.py
from django.urls import path
from . import views

app_name = 'onlineschool'

urlpatterns = [
    path('', views.index, name='index'),
    path('user_list', views.user_list, name='user_list'),
    path('user_form', views.user_form, name='user_form'),
    path('user_form/<int:user_id>/', views.user_edit, name='user_edit'),
    path('user_delete/<int:user_id>/', views.user_delete, name='user_delete'),
    path('lesson_list', views.lesson_list, name='lesson_list'),
    path('lesson_form', views.lesson_form, name='lesson_form'),
    path('lesson_form/<int:lesson_id>/', views.lesson_edit, name='lesson_edit'),
    path('lesson_delete/<int:lesson_id>/', views.lesson_delete, name='lesson_delete'),
    path('lesson_invoice', views.lesson_invoice, name='lesson_invoice'),
    path('lesson_report', views.lesson_report, name='lesson_report'),
]

onlineschool/models.py
from django.db import models
from django.utils import timezone
from django import forms


class User(models.Model):
    SEX_CHOICES = (
        ('男', '男'),
        ('女', '女'),
    )

    class Meta:
        db_table = 'user'

    name = models.CharField(verbose_name='名前', max_length=255)
    sex = models.CharField(verbose_name='性別', max_length=255)
    age = models.IntegerField(verbose_name='年齢')

    def __str__(self):
        return self.name


class Lesson(models.Model):
    class Meta:
        db_table = 'lesson'

    name = models.CharField(verbose_name='名前', max_length=255)
    basic_charge = models.IntegerField(verbose_name='基本料金')
    pay_per_charge = models.IntegerField(verbose_name='従量料金')
    free_time = models.IntegerField(default=0, verbose_name='無料時間')

    def __str__(self):
        return self.name


class LessonRecord(models.Model):
    class Meta:
        db_table = 'lessonrecord'

    user_name = models.ForeignKey(User, verbose_name='顧客名', on_delete=models.CASCADE)
    lesson_name = models.ForeignKey(Lesson, verbose_name='ジャンル名', on_delete=models.CASCADE)
    lesson_date = models.DateField(default=timezone.now, verbose_name='受講日')
    lesson_hour = models.IntegerField(verbose_name='受講時間')
    lesson_charge = models.IntegerField(default=0, verbose_name='受講料金')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.cleaned_lesson_hour = None

    def clean_lesson_hour(self):
        lesson_hour = self.cleaned_lesson_hour['lesson_hour']
        if 0 >= lesson_hour > 12:
            raise forms.ValidationError(
                '0-12時間の間で入力してください'
            )
        return lesson_hour


class Discount(models.Model):
    class Meta:
        db_table = 'discount'

    lesson_name = models.ForeignKey(Lesson, verbose_name='ジャンル名', on_delete=models.CASCADE)
    limited_hour = models.IntegerField(verbose_name='閾時間')
    discount_price = models.IntegerField(verbose_name='割引額')

onlineschool/views.py
from django.db.models import Sum
from django.shortcuts import (
    render,
    get_object_or_404,
)
from django.http import HttpResponseRedirect
from django.urls import reverse
from .models import User, Lesson, LessonRecord, Discount
from .form import UserForm, LessonRecordForm, InvoiceSearchForm
import datetime


def index(request):
    params = {
        'title': 'メニュー',
    }
    return render(request, 'onlineschool/index.html', params)


# ユーザー関連
def user_list(request):
    params = {
        'title': '顧客一覧',
        'users': User.objects.all(),
    }
    return render(request, 'onlineschool/user_list.html', params)


def user_form(request):
    if request.method == 'POST':
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('onlineschool:user_list'))
        else:
            params = {
                'title': '顧客登録',
                'form': form
            }
            return render(request, 'onlineschool/user_new.html', params)
    else:
        params = {
            'title': '顧客登録',
            'form': UserForm()
        }
    return render(request, 'onlineschool/user_new.html', params)


def user_edit(request, user_id):
    user = get_object_or_404(User, pk=user_id)
    if request.method == 'POST':
        form = UserForm(request.POST, instance=user)
        if form.is_valid():
            user.save()
            return HttpResponseRedirect(reverse('onlineschool:user_list'))
    else:
        form = UserForm({'name': user.name, 'sex': user.sex, 'age': user.age})
        params = {
            'title': '顧客編集',
            'form': form,
            'user_id': user_id,
        }
    return render(request, 'onlineschool/user_edit.html', params)


def user_delete(request, user_id):
    user = get_object_or_404(User, pk=user_id)
    user.delete()
    params = {
        'title': '顧客一覧',
        'users': User.objects.all(),
    }
    return render(request, 'onlineschool/user_list.html', params)


def lesson_list(request):
    params = {
        'title': 'レッスン一覧',
        'lessonrecords': LessonRecord.objects.all(),
    }
    return render(request, 'onlineschool/lesson_list.html', params)


def lesson_form(request):
    if request.method == 'POST':
        form = LessonRecordForm(request.POST)
        if form.is_valid():
            lesson = form.save()
            lesson_with_charge = LessonRecord.objects.get(pk=lesson.id)
            if total_lesson_hour(lesson_with_charge.lesson_name.pay_per_charge, lesson_with_charge) is None:
                lesson_with_charge.lesson_charge = 0
            else:
                lesson_with_charge.lesson_charge = total_lesson_hour(lesson_with_charge.lesson_name.pay_per_charge, lesson_with_charge)
            lesson_with_charge.save()
            return HttpResponseRedirect(reverse('onlineschool:lesson_list'))
        else:
            return render(request, 'onlineschool/lesson_new.html', {'form': form})
    else:
        params = {
            'title': 'レッスン登録',
            'form': LessonRecordForm()
        }
    return render(request, 'onlineschool/lesson_new.html', params)


def lesson_edit(request, lesson_id):
    lesson = get_object_or_404(LessonRecord, pk=lesson_id)
    if request.method == 'POST':
        form = LessonRecordForm(request.POST, instance=lesson)
        if form.is_valid():
            lesson.save()
            lesson_with_charge = LessonRecord.objects.get(pk=lesson.id)
            lesson_with_charge.lesson_charge = total_lesson_hour(lesson_with_charge.lesson_name.pay_per_charge, lesson_with_charge)
            lesson_with_charge.save()
            return HttpResponseRedirect(reverse('onlineschool:lesson_list'))
    else:
        form = LessonRecordForm({
            'user_name': lesson.user_name.id,
            'lesson_name': lesson.lesson_name.id,
            'lesson_date': lesson.lesson_date,
            'lesson_hour': lesson.lesson_hour,
        })
        params = {
            'title': 'レッスン編集',
            'form': form,
            'lesson_id': lesson_id,
        }
    return render(request, 'onlineschool/lesson_edit.html', params)


def lesson_delete(request, lesson_id):
    lesson = get_object_or_404(LessonRecord, pk=lesson_id)
    lesson.delete()
    params = {
        'title': 'レッスン一覧',
        'lessonrecords': LessonRecord.objects.all(),
    }
    return render(request, 'onlineschool/lesson_list.html', params)


def lesson_invoice(request):
    if request.method == 'POST':
        params = {
            'title': request.POST['invoice_search'] + '月レッスン請求一覧',
            'users': User.objects.all(),
            'form': InvoiceSearchForm(),
            'lesson_search_month': request.POST['invoice_search']
        }
        return render(request, 'onlineschool/lesson_invoice.html', params)
    else:
        params = {
            'title': 'レッスン請求一覧',
            'users': User.objects.all(),
            'form': InvoiceSearchForm(),
            'lesson_search_month': datetime.date.today().month
        }
        return render(request, 'onlineschool/lesson_invoice.html', params)


def lesson_report(request):
    summarize_genre_sex = []
    for genre in Lesson.objects.all().values_list('name', flat=True).order_by('name').distinct().reverse():
        for sex in User.objects.all().values_list('sex', flat=True).order_by('sex').distinct().reverse():
            summarize_genre_sex.append([genre, sex])

    summarize_genre_sex_age = []
    age_list = ["10", "20", "30", "40", "50", "60", "70"]
    for genre in Lesson.objects.all().values_list('name', flat=True).order_by('name').distinct().reverse():
        for sex in User.objects.all().values_list('sex', flat=True).order_by('sex').distinct().reverse():
            for age in age_list:
                summarize_genre_sex_age.append([genre, sex, age])

    if request.method == 'POST':
        params = {
            'title': request.POST['invoice_search'] + '月レッスンレポート',
            'summarize_genre_sex': summarize_genre_sex,
            'summarize_genre_sex_age': summarize_genre_sex_age,
            'users': User.objects.all(),
            'form': InvoiceSearchForm(),
            'lesson_search_month': request.POST['invoice_search']
        }
        return render(request, 'onlineschool/lesson_report.html', params)
    else:
        params = {
            'title': 'レッスンレポート',
            'summarize_genre_sex': summarize_genre_sex,
            'summarize_genre_sex_age': summarize_genre_sex_age,
            'users': User.objects.all(),
            'form': InvoiceSearchForm(),
            'lesson_search_month': datetime.date.today().month
        }
        return render(request, 'onlineschool/lesson_report.html', params)


def total_lesson_hour(lesson_pay, lesson):
    # 現在の合計受講時間をユーザー・レッスン・月別に集計
    total_lesson_hour = LessonRecord.objects.all().filter(
        lesson_name=lesson.lesson_name,
        user_name=lesson.user_name,
        lesson_date__month=lesson.lesson_date.month,
        id__lte=lesson.id
    ).aggregate(Sum('lesson_hour'))

    # 前回までの合計受講時間をユーザー・レッスン・月別に集計
    previous_total_lesson_hour = LessonRecord.objects.all().filter(
        lesson_name=lesson.lesson_name,
        user_name=lesson.user_name,
        lesson_date__month=lesson.lesson_date.month,
        id__lt=lesson.id
    ).aggregate(Sum('lesson_hour'))

    discount_rate = Discount.objects.order_by('-limited_hour').filter(lesson_name_id=lesson.lesson_name.id)
    discount_rate_list = list(discount_rate)
    discount_level_count = 0

    # 月の受講が初めての時、基本受講料を追加
    if previous_total_lesson_hour['lesson_hour__sum'] is None:
        final_lesson_charge = lesson.lesson_name.basic_charge
    else:
        final_lesson_charge = 0

    # もし割引がない時、従量基本料金で計算
    if not discount_rate_list:
        final_lesson_charge += lesson.lesson_hour * lesson_pay
        return final_lesson_charge

    # もし割引がある時、従量基本料金にいくら割引するか計算
    for discount_info in discount_rate:
        # 合計受講時間が閾値以上あるとき
        if total_lesson_hour['lesson_hour__sum'] >= discount_info.limited_hour:
            deff_from_limited = total_lesson_hour['lesson_hour__sum'] - discount_rate_list[0].limited_hour

            if len(discount_rate) - 1 != discount_level_count:
                lesson_pay = discount_rate[discount_level_count + 1].discount_price

            # 受講時間が閾値をまたいでいない時
            if lesson.lesson_hour - deff_from_limited < 0:
                final_lesson_charge = lesson.lesson_hour * discount_rate_list[0].discount_price
            # 受講時間が閾値をまたいでいる時
            else:
                # 閾値を超えた分は割引額で計算
                final_lesson_charge += deff_from_limited * discount_rate_list[0].discount_price
                # 閾値以下分は割引前の額で計算
                final_lesson_charge += (lesson.lesson_hour - deff_from_limited) * lesson_pay
            return final_lesson_charge

        # 合計受講時間が閾値以下の時
        else:
            # 合計受講時間が最小割引閾値を超えない時
            if len(discount_rate_list) == 1:
                # ジャンルに無料時間が設定されている時
                if lesson.lesson_name.free_time > 0:
                    # 受講が初めての時
                    if previous_total_lesson_hour['lesson_hour__sum'] is None:
                        # 受講時間は無料時間を超えているか
                        if lesson.lesson_hour > lesson.lesson_name.free_time:
                            final_lesson_charge += (lesson.lesson_hour - lesson.lesson_name.free_time) * lesson_pay
                    # 受講が2回目以降
                    else:
                        # 前回の受講が無料時間を超えておらず、今回無料時間を超えた時
                        if previous_total_lesson_hour['lesson_hour__sum'] < lesson.lesson_name.free_time and total_lesson_hour['lesson_hour__sum'] > lesson.lesson_name.free_time:
                            final_lesson_charge += (lesson.lesson_hour - (lesson.lesson_name.free_time - previous_total_lesson_hour['lesson_hour__sum'])) * lesson_pay
                        else:
                            final_lesson_charge += lesson.lesson_hour * lesson_pay

onlineschool/templates/onlineschool/base.html
{% load static %}
<!doctype html>
<html lang="ja">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width,initial-scale=1,user-scalable=no">
        <title>onlineschool</title>
        <link rel="stylesheet" type="text/css"
        href="{% static 'onlineschool/css/reset.css' %}"/>
        <link rel="stylesheet" type="text/css"
        href="{% static 'onlineschool/css/style.css' %}"/>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    </head>
    <body>
    <div class="container pt-5 pb-5">
        {% block body %}
        {% endblock %}
    </div>
    </body>
</html>

onlineschool/templates/onlineschool/index.html
{% extends "onlineschool/base.html" %}
{% block body %}
<h1 class="title">{{title}}</h1>
<ul>
    <li><a href="{% url 'onlineschool:user_list' %}">顧客一覧</a></li>
    <li><a href="{% url 'onlineschool:lesson_list' %}">レッスン受講記録</a></li>
    <li><a href="{% url 'onlineschool:lesson_invoice' %}">月別請求一覧</a></li>
    <li><a href="{% url 'onlineschool:lesson_report' %}">レポート</a></li>
</ul>
{% endblock %}

onlineschool/templates/onlineschool/lesson_edit.html
{% extends "onlineschool/base.html" %}
{% block body %}
<h1>{{title}}</h1>

<form action= "{% url 'onlineschool:lesson_edit' lesson_id=lesson_id %}" method = "post">
    {% for field in form%}
    <div class="field">
        <div class="ui input">
            {{ field.label_tag}}
            {% csrf_token %}
            {{field}}
        </div>
        {% if field.errors%}
        <p class="red message">
            {{ field.errors.0 }}
        </p> {% endif%}
    </div>
    {% endfor%}
    <input type="submit" value="編集" class="btn btn-secondary mb-2">
</form>
{% if form.non_field_errors%}
<div class="ui red message">
    <ul class="list">
        {% for non_field_error in form.non_field_errors%}
        <li>{{ non_field_error }}</li>
        {% endfor%}
    </ul>
</div>
{% endif%}
{% endblock %}

onlineschool/templates/onlineschool/lesson_invoice.html
{% extends "onlineschool/base.html" %}
{% load extras %}
{% block body %}
<h1>{{title}}</h1>
<form action= "{% url 'onlineschool:lesson_invoice' %}" method = "post" class="input-group mb-5 mt-5">
    {% for field in form %}
    <div class="field">
        <div class="ui input form-control">
            {{ field.label_tag}}
            {% csrf_token %}
            {{field}}
        </div>
        {% if field.errors%}
        <p class="red message">
            {{ field.errors.0 }}
        </p> {% endif%}
    </div>
    {% endfor%}
    <span class="input-group-btn">
        <input type="submit" value="検索" class="btn btn-secondary">
    </span>
</form>
<div class="table-responsive">
  <table class="table table-hover table-condensed table-bordered table-striped">
    <thead>
    <tr>
      <th>顧客ID</th>
      <th>顧客名</th>
      <th>ジャンル</th>
      <th>合計レッスン数</th>
      <th>請求金額</th>
    </tr>
    </thead>
    <tbody>
      {% for user in users %}
    <tr>
      <td>{{ user.id }}</td>
      <td>{{ user.name }}</td>
      <td>{{ lesson_search_month|month_lesson_genre:user }}</td>
      <td>{{ lesson_search_month|month_lesson_count:user }}レッスン</td>
      <td>{{ lesson_search_month|month_lesson_charge:user }}</td>
    </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
<div class="text-center">
<a href="{% url 'onlineschool:index' %}" class="btn btn-secondary mb-1">トップに戻る</a>
</div>
{% endblock %}

onlineschool/templates/onlineschool/lesson_list.html
{% extends "onlineschool/base.html" %}
{% load extras %}
{% block body %}
<h1>{{title}}</h1>
<div class="table-responsive">
  <table class="table table-hover table-condensed table-bordered table-striped">
    <thead>
    <tr>
      <th>ID</th>
      <th>顧客名</th>
      <th>ジャンル</th>
      <th>日付</th>
      <th>受講時間</th>
      <th>支払い金額</th>
      <th></th>
    </tr>
    </thead>
    <tbody>
      {% for lesson in lessonrecords %}
    <tr>
      <td>{{ lesson.id }}</td>
      <td>{{ lesson.user_name }}</td>
      <td>{{ lesson.lesson_name }}</td>
      <td>{{ lesson.lesson_date }}</td>
      <td>{{ lesson.lesson_hour }}</td>
      <td>{{ lesson.lesson_charge }}</td>
      <td>
        <a href="{% url 'onlineschool:lesson_edit' lesson_id=lesson.id %}" class="btn-sm btn-secondary mb-1">編集</a>
        <a href="{% url 'onlineschool:lesson_delete' lesson_id=lesson.id %}" class="btn-sm btn-secondary mb-1">削除</a>
      </td>
    </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
<div class="text-center">
<a href="{% url 'onlineschool:index' %}" class="btn btn-secondary mb-1">トップに戻る</a>
<a href="{% url 'onlineschool:lesson_form' %}" class="btn btn-secondary mb-1">新規追加</a>
</div>
{% endblock %}

onlineschool/templates/onlineschool/lesson_new.html
{% extends "onlineschool/base.html" %}
{% block body %}
<h1>{{title}}</h1>

<form action= "{% url 'onlineschool:lesson_form' %}" method = "post">
    {% for field in form %}
    <div class="field">
        <div class="ui input">
            {{ field.label_tag}}
            {% csrf_token %}
            {{field}}
        </div>
        {% if field.errors%}
        <p class="red message">
            {{ field.errors.0 }}
        </p> {% endif%}
    </div>
    {% endfor%}
    <input type="submit" value="登録" class="btn btn-secondary mb-2">
</form>
{% if form.non_field_errors%}
<div class="ui red message">
    <ul class="list">
        {% for non_field_error in form.non_field_errors%}
        <li>{{ non_field_error }}</li>
        {% endfor%}
    </ul>
</div>
{% endif%}
{% endblock %}

onlineschool/templates/onlineschool/lesson_report.html
{% extends "onlineschool/base.html" %}
{% load extras %}
{% block body %}
<h1>{{title}}</h1>
<form action= "{% url 'onlineschool:lesson_report' %}" method = "post" class="input-group mb-5 mt-5">
    {% for field in form %}
    <div class="field">
        <div class="ui input form-control">
            {{ field.label_tag }}
            {% csrf_token %}
            {{field}}
        </div>
        {% if field.errors %}
        <p class="red message">
            {{ field.errors.0 }}
        </p> {% endif %}
    </div>
    {% endfor%}
    <span class="input-group-btn">
        <input type="submit" value="検索" class="btn btn-secondary">
    </span>
</form>

<h2>ジャンルと性別別</h2>
<div class="table-responsive mb-4">
  <table class="table table-hover table-condensed table-bordered table-striped">
    <thead>
    <tr>
      <th>ジャンル</th>
      <th>性別</th>
      <th>レッスン数</th>
      <th>受講者数</th>
      <th>売り上げ</th>
    </tr>
    </thead>
    <tbody>
      {% for ele_genre_sex in summarize_genre_sex %}
    <tr>
      <td>{{ ele_genre_sex.0 }}</td>
      <td>{{ ele_genre_sex.1 }}</td>
      <td>{{ lesson_search_month|month_lesson_count_genre_sex:ele_genre_sex }}レッスン</td>
      <td>{{ lesson_search_month|month_user_count_genre_sex:ele_genre_sex }}人</td>
      <td>{{ lesson_search_month|month_lesson_charge_genre_sex:ele_genre_sex }}</td>
    </tr>
      {% endfor %}
    </tbody>
  </table>
</div>

<h2>ジャンルと年齢層別</h2>
<div class="table-responsive">
  <table class="table table-hover table-condensed table-bordered table-striped">
    <thead>
    <tr>
      <th>ジャンル</th>
      <th>性別</th>
      <th>年齢層</th>
      <th>レッスン数</th>
      <th>受講者数</th>
      <th>売り上げ</th>
    </tr>
    </thead>
    <tbody>
      {% for ele_genre_sex_age in summarize_genre_sex_age %}
    <tr>
      <td>{{ ele_genre_sex_age.0 }}</td>
      <td>{{ ele_genre_sex_age.1 }}</td>
      <td>{{ ele_genre_sex_age.2 }}代</td>
      <td>{{ lesson_search_month|month_lesson_count_genre_sex_age:ele_genre_sex_age }}レッスン</td>
      <td>{{ lesson_search_month|month_user_count_genre_sex_age:ele_genre_sex_age }}人</td>
      <td>{{ lesson_search_month|month_lesson_charge_genre_sex_age:ele_genre_sex_age }}</td>
    </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
<div class="text-center">
<a href="{% url 'onlineschool:index' %}" class="btn btn-secondary mb-1">トップに戻る</a>
</div>
{% endblock %}

onlineschool/templates/onlineschool/user_edit.html
{% extends "onlineschool/base.html" %}
{% block body %}
<h1>{{ title }}</h1>

<form action= "{% url 'onlineschool:user_edit' user_id=user_id %}" method = "post">
    {% for field in form %}
    <div class="field">
        <div class="ui input">
            {{ field.label_tag }}
            {% csrf_token %}
            {{field}}
        </div>
        {% if field.errors %}
        <p class="red message">
            {{ field.errors.0 }}
        </p> {% endif %}
    </div>
    {% endfor %}
    <input type="submit" value="編集" class="btn btn-secondary mb-2">
</form>
{% if form.non_field_errors %}
<div class="ui red message">
    <ul class="list">
        {% for non_field_error in form.non_field_errors %}
        <li>{{ non_field_error }}</li>
        {% endfor%}
    </ul>
</div>
{% endif%}
{% endblock %}

onlineschool/templates/onlineschool/user_list.html
{% extends "onlineschool/base.html" %}
{% block body %}
<h1>{{title}}</h1>
<div class="table-responsive">
  <table class="table table-hover table-condensed table-bordered table-striped">
    <thead>
    <tr>
      <th>ID</th>
      <th>名前</th>
      <th>性別</th>
      <th>年齢</th>
      <th> </th>
    </tr>
    </thead>
    <tbody>
      {% for user in users %}
    <tr>
      <td>{{ user.id }}</td>
      <td>{{ user.name }}</td>
      <td>{{ user.sex }}</td>
      <td>{{ user.age }}</td>
      <td>
        <a href="{% url 'onlineschool:user_edit' user_id=user.id %}" class="btn-sm btn-secondary mb-1">編集</a>
        <a href="{% url 'onlineschool:user_delete' user_id=user.id %}" class="btn-sm btn-secondary mb-1">削除</a>
      </td>
    </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
<div class="text-center">
  <a href="{% url 'onlineschool:index' %}" class="btn btn-secondary mb-1">トップに戻る</a>
  <a href="{% url 'onlineschool:user_form' %}" class="btn btn-secondary mb-1">新規追加</a>
</div>
{% endblock %}

onlineschool/templates/onlineschool/user_new.html
{% extends "onlineschool/base.html" %}
{% block body %}
<h1>{{title}}</h1>

<form action= "{% url 'onlineschool:user_form' %}" method = "post">
    {% for field in form %}
    <div class="field">
        <div class="ui input">
            {{ field.label_tag}}
            {% csrf_token %}
            {{field}}
        </div>
        {% if field.errors%}
        <p class="red message">
            {{ field.errors.0 }}
        </p> {% endif %}
    </div>
    {% endfor %}
    <input type="submit" value="登録" class="btn btn-secondary mb-2">
</form>
{% if form.non_field_errors %}
<div class="ui red message">
    <ul class="list">
        {% for non_field_error in form.non_field_errors%}
        <li>{{ non_field_error }}</li>
        {% endfor%}
    </ul>
</div>
{% endif%}
{% endblock %}